### ISSUE TITLE
Respiration project 

### ISSUE THREAD

**Issue by AlexisRenchon** [CUPofTEAproject/www.cupoftea.earth#4]
- [x] FNDAMM on website #25 
- [x] Normalize #27 
- [x] Adjust axes limits #28 
- [x] Fix the poro_value issue --> WIP: posted MWE on Julia Slack and Discourse. --> if no solution on Discourse, I can always create a function that gets `FNDAMMfit` output for a site ID oustide of Observable, so that it won't crash when poro_val is an Observable #29 
- [x] Add more FLUXNET sites #32 
- [x] Find a way to filter out sites with missing data (e.g., missing Tsoil) --> TO DO: find index of site with data, then create a new getID() that goes from 1:n with the ID of those site than contain data --> DONE locally, FLUXNET_plot.jl, just need to create function, redo figure, commit. #32 
- [x] Filter for measured data only (qc = 0 according to Pastorello et al. 2020) #33 
- [x] DAMM and qbin should be called from DAMMmodel.jl (not calling script from /functions/, use DAMM from original model, see https://github.com/JuliaNLSolvers/LsqFit.jl/issues/201).  #34 
- [ ] Optimize the scripts and folder structure 
- [ ] Add a legend (what the dots and surface are)
- [ ] Make MWE for WGLMakie/JSServe menu and clickable button
- [ ] Instead of slider, menu database (e.g., COSORE, FLUXNET), country (e.g., AU, US), site (e.g., Tum, Har)
- [ ] Give parameter values in a text below that can be copy pasted (Franklin can evaluate Julia code to give this)
- [ ] Also give metadata about site (e.g., biome, climate, etc.)
- [ ] Normalize or not as a tickbox widget 
- [ ] fix color of dots issue
- [ ] Curve: more transparent
- [ ] Same for COSORE
- [ ] Same for CMIP6
- [ ] Parameters boxplot per climate

As described in the main page, create apparent response on respiration to soil temperature and moisture, for ecosystem and soil, data (FLUXNET, COSORE) and model (CMIP6).

**Comment by AlexisRenchon** [comment]
quantilebins.jl script done f6cc311.
next: 
1. script to normalize R to 10, M to 0-100
2. script WGLMakie to plot R = f(T,M) for each of FLUXNET site (slider), then COSORE, then CMIP6
3. script parameter: sensitivity to T and M (oxygen and substrate), DAMM of just slope
4. script parameter per biome and climate, ecosystem and soil, data and model

**Comment by AlexisRenchon** [comment]
Started working plotting R=F(T,M) and DAMMfit for FLUXNET sites in fe6f25e.

**Comment by AlexisRenchon** [comment]
Progress in #21 
To do: create plot for WGLMakie, upload on website

**Comment by AlexisRenchon** [comment]
More progress in #22 
To do: finalize fixes to make interactive plot work in GLMakie, then transfer to WGLMakie, then upload on Franklin
